# This file was generated by GoReleaser. DO NOT EDIT.
class OpsaniCli < Formula
  desc "Opsani CLI"
  homepage "https://github.com/opsani/cli"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/opsani/cli/releases/download/v0.1.1/opsani-cli_0.1.1_macOS_amd64.tar.gz"
    sha256 "6e8fb81e81bd5f542756ba4661928e6bc1279eb0998904a5a5c924a17d3b0c02"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/opsani/cli/releases/download/v0.1.1/opsani-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "1cf08a8132ac484d43689a531ba83c7682cbe5a933e55584538ac4b696cd34c7"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opsani/cli/releases/download/v0.1.1/opsani-cli_0.1.1_linux_arm64.tar.gz"
        sha256 "7b922c05010bf6d05cdd21e7f6af1911b2b8484ef3a679fbc2abed25f1f809fb"
      else
      end
    end
  end
  
  head do
    url "https://github.com/opsani/cli.git"
    depends_on "go"
  end

  def install
    system "make build" if build.head?
    bin.install "bin/opsani"
    (bash_completion/"opsani.sh").write `#{bin}/opsani completion -s bash`
    (zsh_completion/"_opsani").write `#{bin}/opsani completion -s zsh`
    (fish_completion/"opsani.fish").write `#{bin}/opsani completion -s fish`
  end

  test do
    help_text = shell_output("#{bin}/opsani --help")
    assert_includes help_text, "Usage:"
  end
end
