# This file was generated by GoReleaser. DO NOT EDIT.
class OpsaniCli < Formula
  desc "Opsani CLI"
  homepage "https://github.com/opsani/cli"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/opsani/cli/releases/download/v0.1.0/opsani-cli'_0.1.0_macOS_amd64.tar.gz"
    sha256 "d0bfce16089dc2bf14f4a445ae599f738a1a7eee62c56a79be8a5ef1f174e26b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/opsani/cli/releases/download/v0.1.0/opsani-cli'_0.1.0_linux_amd64.tar.gz"
      sha256 "7e0b0c6f04317ea8d7570419fd8acc31735fc91a476e77249369c1e6d2b228d4"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opsani/cli/releases/download/v0.1.0/opsani-cli'_0.1.0_linux_arm64.tar.gz"
        sha256 "f6fee34c46ecdfcdbab13136771de718712d26bb3f089b1d428d0e100956b934"
      else
      end
    end
  end
  
  head do
    url "https://github.com/opsani/cli.git"
    depends_on "go"
  end

  def install
    system "make build" if build.head?
    bin.install "bin/opsani"
    (bash_completion/"opsani.sh").write `#{bin}/opsani completion -s bash`
    (zsh_completion/"_opsani").write `#{bin}/opsani completion -s zsh`
    (fish_completion/"opsani.fish").write `#{bin}/opsani completion -s fish`
  end

  test do
    help_text = shell_output("#{bin}/opsani --help")
    assert_includes help_text, "Usage:"
  end
end
